// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// The app keeps its secrets in .env.local (Clerk keys, DATABASE_URL). Point the
// Prisma CLI at it so `prisma migrate`/`db push` can read DATABASE_URL.
// Next.js loads .env.local on its own at runtime.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
